
import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/custom/theme-provider";
import { SiteHeader } from "@/components/custom/site/navbar/header";
import { ScrollProgress } from "@/components/magicui/scroll-progress";
import ClickSpark from "@/components/click-spark";

const font = Bricolage_Grotesque({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Devlox Studio | Transforming your Ideas into Apps",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${font.className} antialiased`}
      >
        <ClickSpark
  sparkColor='#fff'
  sparkSize={10}
  sparkRadius={15}
  sparkCount={8}
  duration={400}
>
        <ScrollProgress/>
        <SiteHeader/>
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex h-full w-full">
            {children}
            </div>
          </ThemeProvider>
          </ClickSpark>
      </body>
    </html>
  );
}
